spring:

  batch:
    initialize-schema: always
    job:
      names: flowJob1
  #      names: ${job.name:NONE} # 어떤 잡을 실행할지 지정 x, 외부에서 알려줘야함.
  #   names: testJob1 <- 이 job만 수행함.
  #      enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
