spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/batchTest

  batch:
    initialize-schema: never


logging:
  level:
    sql: debug

